### ISSUE TITLE
[Android] Build Exception

### ISSUE THREAD

**Issue by divyaponnurucmsedge** [PDFTron/pdftron-react-native#113]
FAILURE: Build failed with an exception.

* Where:
Script 'E:\NativeApps\PdfTron\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195
* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1032  throw err;  ^Error: Cannot find module 'E:\NativeApps\PdfTron\android\undefined'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)    at Function.Module._load (internal/modules/cjs/loader.js:898:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (E:\NativeApps\PdfTron\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (E:\NativeApps\PdfTron\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at E:\NativeApps\PdfTron\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (E:\NativeApps\PdfTron\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:7)

**Comment by divyaponnurucmsedge** [comment]
please help me to solve that issue

**Comment by divyaponnurucmsedge** [comment]
please help me to solve that issue

**Comment by sgong-pdftron** [comment]
@divyaponnurucmsedge 
1. please make sure your app can run before adding this module
2. please follow https://github.com/PDFTron/pdftron-react-native#installation step by step

The error shown doesn't really have anything to do with this module. So it likely means your project is not setup correctly. Thanks.
