### ISSUE TITLE
FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by brerdem** [PDFTron/pdftron-react-native#447]
**Describe the bug**
When trying to open a document the app crashes and Logcat throws "FragmentManager is already executing transactions" error.

Platform: Android
PDFTron version: com.pdftron:pdftron:9.1.2-beta09

Output:
```
Process: ch.bvsbuchverlag.ebookbox, PID: 24466
    java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1778)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1814)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at com.pdftron.pdf.controls.DocumentView2.prepView(DocumentView2.java:124)
        at com.pdftron.pdf.controls.DocumentView2.onAttachedToWindow(DocumentView2.java:152)
        at com.pdftron.reactnative.views.DocumentView.onAttachedToWindow(DocumentView.java:1839)
        at android.view.View.dispatchAttachedToWindow(View.java:22010)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:6108)
        at android.view.ViewGroup.addView(ViewGroup.java:5884)
        at android.view.ViewGroup.addView(ViewGroup.java:5824)
        at android.view.ViewGroup.addView(ViewGroup.java:5796)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:326)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by sgong-pdftron** [comment]
@brerdem could you please provide a sample project as well as step to reproduce (with a video ideally) so we can investigate on our end? Thanks.

**Comment by brerdem** [comment]
It's a confidential project and probably I can't share the whole code or making a sample out of it. I'll ask managers about it though. For now, here is the reproduction video

https://user-images.githubusercontent.com/778976/148042193-7c61103f-46db-49a7-99e0-b82d3ae81345.mp4

I'm using react-navigation v6.x and don't use any layout animation or react-native-reanimated which I was suspicious of being the cause of the issue. I'm testing on a real device with Android 11 and so far only on debug mode. Never built for production. 



Here is also the page that shows the document

````
// @flow

import React, {useEffect, useMemo, useRef, useState} from 'react';
import {Config, DocumentView, RNPdftron} from 'react-native-pdftron';
import {useData} from '../../providers/DataProvider';
import {
  getAnnotsXMLString,
  getCurrentAnnotXML,
  getInitialLetters,
  hexToRgb,
} from '../../../utils/functions';
import BottomSheet from '../../shared/BottomSheet';
import AnnotationContext from '../../annotation/AnnotationContext';
import {useUser} from '../../providers/UserProvider';
import api from '../../../utils/api';
import {isNil, values, without} from 'ramda';
import {showMessage} from 'react-native-flash-message';
import {
  ActivityIndicator,
  StyleSheet,
  useWindowDimensions,
  View,
} from 'react-native';
import {
  Avatar,
  Button,
  Icon,
  Input,
  ListItem,
  Overlay,
  Text,
  useTheme,
} from 'react-native-elements';
import {Sizes} from '../../../utils/constants';
import SpacedView from '../../shared/SpacedView';
import {useNetInfo} from '@react-native-community/netinfo';
import {useDispatch, useSelector} from 'react-redux';
import firestore from '@react-native-firebase/firestore';
import {setHeight} from '../../../redux/slicers/height';

const ViewBook = ({navigation, route}) => {
  const {annots, docs} = useData();

  const [documentLoaded, setDocumentLoaded] = useState(false);
  const [contextOpen, setContextOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [selectedAnnot, setSelectedAnnot] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [userPopupOpen, setUserPopupOpen] = useState(false);
  const {isConnected} = useNetInfo();
  const downloads = useSelector(state => state.downloads);
  const dispatch = useDispatch();

  const db = firestore();

  const id = route.params?.id;
  const page = route.params?.page;

  const {user} = useUser();
  const viewer = useRef(null);

  const {width} = useWindowDimensions();

  const {
    theme: {colors},
  } = useTheme();

  const docPath = useMemo(() => {
    if (route.params.id && !isNil(isConnected)) {
      return isConnected
        ? docs.find(x => x.id === route.params.id).url
        : downloads.find(x => x.id === route.params.id).path;
    }
    return 'https://firebasestorage.googleapis.com/v0/b/ebookbox-bvs.appspot.com/o/files%2Fbookbox.pdf?alt=media&token=2ab62b00-0324-47ab-a66b-293d3c002654';
  }, [route.params, docs, isConnected, downloads]);

  const docAnnots = useMemo(() => {
    if (route.params.id) {
      return annots.filter(x => x.docId === route.params.id);
    }
  }, [route.params, annots]);

  const importAnnots = async xmlString => {
    await viewer.current.importAnnotations(xmlString);
  };

  const annotSave = async (annotId, annotXMLStr) => {
    console.log('annotId -->', annotId);

    const annotData = {
      id: annotId,
      owner: user.email,
      ownerName: user.displayName,
      docId: id,
      availableTo: [user.email],
      favoriteTo: [],
      addDate: new Date().toISOString(),
      xmlStr: annotXMLStr,
    };

    console.log('annotdata -->', JSON.stringify(annotData));

    try {
      const response = await api.post('/annot/add', {
        annotData,
      });
      if (response.data.success) {
        console.log('annot saved -->');
      } else {
        showMessage({
          message: 'There was a problem saving the note. Please try again.',
          icon: 'warning',
          type: 'danger',
        });
      }
    } catch (e) {
      console.log('e -->', e);
    }
  };

  const handleChangeText = text => {
    setSearchTerm(text);
  };

  const annotModify = async (annotId, annotXMLStr) => {
    const response = await api.put('/annot/modify', {
      annotId,
      annotXMLStr,
    });
    if (response.data.success) {
      console.log('annot modified -->');
    } else {
      showMessage({
        message: 'There was a problem updating the note',
        icon: 'warning',
        type: 'danger',
      });
    }
  };

  const deleteSub = async ref => {
    const snapshot = await ref.get();

    if (!snapshot.empty) {
      const batch = db.batch();
      snapshot.docs.forEach(doc => {
        batch.delete(doc.ref);
      });
      await batch.commit();
    }
  };

  const annotDelete = async (annot, fromContext = false) => {
    /*  const id = selectedAnnot ? selectedAnnot.id : annotId;
    const pageNumber = selectedAnnot ? selectedAnnot.pageNumber : pNumber;*/
    const {id, pageNumber, type} = annot;

    setDeleting(true);

    const annotRef = db.collection('annots').doc(id);

    try {
      if (type === 'AnnotationCreateFreeHighlighter') {
        const annotRepliesRef = annotRef.collection('replies');
        const annotLinksRef = annotRef.collection('links');

        await deleteSub(annotRepliesRef);
        await deleteSub(annotLinksRef);
      }

      await annotRef.delete();

      await viewer.current.deleteAnnotations([{id, pageNumber}]);
      if (fromContext) {
        await viewer.current.setToolMode(Config.Tools.pan);
      }
    } catch (error) {
      showMessage({
        message: 'There was a problem deleting the note. Please try again.',
        icon: 'warning',
        type: 'danger',
      });
    }

    setDeleting(false);
    setContextOpen(false);
  };

  const onColorChange = async hexColor => {
    try {
      await viewer.current.setPropertiesForAnnotation(
        selectedAnnot.id,
        selectedAnnot.pageNumber,
        {
          strokeColor: hexToRgb(hexColor),
        },
      );
    } catch (e) {
      console.log('e -->', e);
    }
  };

  const handleSelectAnnotation = async val => {
    const annot = val.annotations[0];

    if (annot && annot.type === 'AnnotationCreateFreeHighlighter') {
      const props = await viewer.current.getPropertiesForAnnotation(
        annot.id,
        annot.pageNumber,
      );
      console.log('props -->', props);

      const tempAnnot = annots.find(x => x.id === annot.id);

      setSelectedAnnot({...tempAnnot, pageNumber: annot.pageNumber});
      setTimeout(() => setContextOpen(true), 200);
    }
  };

  const closeContext = () => {
    setSelectedAnnot(null);
    setContextOpen(false);
  };

  const handleExportAnnotCommand = async ({
    action,
    xfdfCommand,
    annotations,
  }) => {
    console.log('action, xfdf -->', action, xfdfCommand);
    const currentAnnot = annotations[0];
    if (
      [
        'AnnotationCreateFreeHighlighter',
        'AnnotationCreateFreeHand',
        'AnnotationCreateFreeText',
      ].includes(currentAnnot.type)
    ) {
      const annotId = currentAnnot.id;
      if (annotId) {
        switch (action) {
          case 'add':
            await annotSave(annotId, getCurrentAnnotXML(xfdfCommand, 'modify'));
            break;

          case 'modify':
            await annotModify(
              annotId,
              getCurrentAnnotXML(xfdfCommand, 'modify'),
            );
            break;

          case 'delete':
            await annotDelete(currentAnnot);
            break;
        }
      }
    }
  };

  const startSearch = async () => {
    const res = await viewer.current.findText(
      searchTerm,
      false,
      false,
      true,
      false,
    );
  };

  const showUserPopup = () => {
    setUserPopupOpen(true);
  };

  const openOutlineList = async () => {
    if (viewer) {
      await viewer.current.openOutlineList();
    }
  };

  const handleDocumentLoad = ({path}) => {
    console.log('path -->', path);
    setDocumentLoaded(true);
  };

  useEffect(() => {
    RNPdftron.initialize(
      'test',
    );
    RNPdftron.enableJavaScript(true);
    RNPdftron.getVersion().then(val => console.log('val -->', val));
  }, []);

  useEffect(() => {
    (async () => {
      if (viewer.current && documentLoaded && docAnnots.length > 0) {
        try {
          const xmlString = getAnnotsXMLString(docAnnots);
          await importAnnots(xmlString);
        } catch (error) {
          console.log('error -->', error);
        }
      }

      if (page) {
        await viewer.current.setCurrentPage(page);
      }
    })();
  }, [documentLoaded, docAnnots, page]);

  return (
    <View style={styles.container}>
      <View style={styles.topBar}>
        {deleting ? (
          <ActivityIndicator size={'small'} style={{paddingHorizontal: 15}} />
        ) : (
          <Button
            icon={{name: 'close'}}
            onPress={() => navigation.goBack()}
            type={'clear'}
          />
        )}
        <Input
          inputContainerStyle={styles.searchField}
          containerStyle={[styles.searchField, {width: width - 160}]}
          inputStyle={{fontSize: 14, paddingLeft: 5, margin: 0}}
          value={searchTerm}
          onChangeText={handleChangeText}
          leftIcon={<Icon type={'ebookbox'} name={'menu-search'} size={22} />}
          leftIconContainerStyle={{paddingLeft: 10}}
          rightIcon={{name: 'send', onPress: () => startSearch()}}
        />
        <SpacedView h={5}>
          <Button
            type={'clear'}
            icon={{name: 'format-list-bulleted'}}
            onPress={openOutlineList}
          />
        </SpacedView>
        <SpacedView h={5}>
          <Avatar
            title={getInitialLetters(user.displayName)}
            rounded
            containerStyle={{backgroundColor: 'orange'}}
            onPress={showUserPopup}
          />
        </SpacedView>
      </View>

      <DocumentView
        ref={viewer}
        document={
          'https://firebasestorage.googleapis.com/v0/b/ebookbox-bvs.appspot.com/o/files%2Fbookbox.pdf?alt=media&token=2ab62b00-0324-47ab-a66b-293d3c002654'
        }
        longPressMenuEnabled={false}
        annotationMenuItems={[]}
        onDocumentLoaded={handleDocumentLoad}
        onAnnotationsSelected={handleSelectAnnotation}
        onAnnotationChanged={({action}) => console.log('action -- ', action)}
        onExportAnnotationCommand={handleExportAnnotCommand}
        currentUser={user?.displayName}
        hideToolbarsOnTap={false}
        hideTopAppNavBar
        hideAnnotationToolbarSwitcher
        bottomToolbarEnabled={false}
        onToolChanged={({previousTool, tool}) => {
          console.log('Tool has been changed from', previousTool, 'to', tool);
        }}
        disabledElements={without(
          [
            'freeHandToolButton',
            'highlightToolButton',
            'freeTextToolButton',
            'outlineListButton',
          ],
          values(Config.Buttons),
        )}
        disabledTools={without(
          [
            'Pan',
            'AnnotationCreateFreeHand',
            'AnnotationCreateFreeHighlighter',
            'AnnotationCreateTextHighlight',
            'AnnotationCreateFreeText',
          ],
          values(Config.Tools),
        )}
      />

      <BottomSheet
        isVisible={contextOpen}
        onClose={closeContext}
        annotId={selectedAnnot?.id}
        deleteLoading={deleting}
        onAnnotDelete={() => annotDelete(selectedAnnot)}>
        <AnnotationContext
          viewer={viewer}
          annot={selectedAnnot}
          onColorChange={onColorChange}
        />
      </BottomSheet>
      <Overlay isVisible={userPopupOpen} overlayStyle={styles.overlay}>
        <Icon
          name={'close'}
          containerStyle={{
            right: 10,
            top: 10,
            position: 'absolute',
            zIndex: 10000,
          }}
          size={20}
          onPress={() => setUserPopupOpen(false)}
        />
        <Text h4>Shared Notes</Text>
        <Text style={{color: colors.grey3, fontSize: 12}}>
          Users that shared notes in this document
        </Text>
        <SpacedView v>
          <ListItem containerStyle={{margin: 0}}>
            <Avatar
              title={getInitialLetters(user.displayName)}
              rounded
              containerStyle={{backgroundColor: 'orange'}}
            />
            <ListItem.Content>
              <ListItem.Title>{user.displayName}</ListItem.Title>
            </ListItem.Content>
          </ListItem>
        </SpacedView>
      </Overlay>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  searchField: {
    paddingHorizontal: Sizes.XS,
    borderRadius: 21,
    backgroundColor: 'white',
    borderWidth: 0,
    borderBottomWidth: 0,
    height: 42,
  },

  topBar: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  overlay: {
    width: '80%',
    backgroundColor: 'white',
    padding: Sizes.MD,
    borderRadius: Sizes.XS,
    overflow: 'hidden',
    minHeight: 200,
  },
});

export default ViewBook;

````


Finally I'm sharing gradle files

**app/build.gradle**

````
apply plugin: "com.android.application"


import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "ch.bvsbuchverlag.ebookbox"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        missingDimensionStrategy 'react-native-camera', 'general'
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        manifestPlaceholders = [pdftronLicenseKey:"BVS Buchverlag und Service AG(bvsbuchverlag.ch):OEM:eBookBox::IA:AMS(20220429):0C7727501F5794D0A333FD7860611FA5F7481E67CD621DDA5C7C5E0726B6B6F5C7"]
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "androidx.multidex:multidex:2.0.1"
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation platform('com.google.firebase:firebase-bom:29.0.3')

    implementation 'com.google.firebase:firebase-analytics'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    implementation "com.pdftron:pdftron:9.1.2-beta09"
    implementation "com.pdftron:tools:9.1.2-beta09"
    implementation "com.pdftron:collab:9.1.2-beta09"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: "com.google.gms.google-services"
````
**build.gradle**

````

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlinVersion = '1.5.0'
        ndkVersion = "21.0.6113669"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.0.2')
        classpath 'com.google.gms:google-services:4.3.10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
            }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url "https://pdftron-maven.s3.amazonaws.com/snapshot" }
    }
}

````

Thanks!

**Comment by sgong-pdftron** [comment]
@brerdem Would you be able to provide us a minimum sample that can be run as-is? Code snippets are good to spot problems but we may spend a lot of time still not be able to replicate what you had originally. It is possible to go through proper support channel https://www.pdftron.com/form/request/ for confidential project. Thanks.

**Comment by brerdem** [comment]
Hello @sgong-pdftron I added you as a collaborator to the minimal repro of the project. Please let me know if it works for you.

Thanks!

**Comment by sgong-pdftron** [comment]
@brerdem thanks for the project, I'm able to reproduce this, as it is not a trivial problem, it will take some time to dig into the issue. Is this blocking your release? If so, when is the release date? Thanks.

**Comment by sgong-pdftron** [comment]
@brerdem as this is a real bug report now, could you please submit a bug report ticket here: https://www.pdftron.com/form/request/? 

Closing in favor of ticketing system https://www.pdftron.com/form/request/
