### ISSUE TITLE
Unable to get provider com.pdftron.pdf.utils.ShareProvider

### ISSUE THREAD

**Issue by ericksoncst** [PDFTron/pdftron-react-native#6]
Hii, My project works perfectly. But in my android 4.4 I'm getting an error.
I was trying to build with Android Studio cuz RN isn't showing this error.
I followed your guide, just in android 4.4 not work
So, in AS I receive this:

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.goread.android, PID: 14924
    java.lang.RuntimeException: Unable to get provider com.pdftron.pdf.utils.ShareProvider: java.lang.ClassNotFoundException: Didn't find class "com.pdftron.pdf.utils.ShareProvider" on path: DexPathList[[zip file "/data/app/br.com.goread.android-8.apk"],nativeLibraryDirectories=[/data/app-lib/br.com.goread.android-8, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5202)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4794)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4734)
        at android.app.ActivityThread.access$1500(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5590)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pdftron.pdf.utils.ShareProvider" on path: DexPathList[[zip file "/data/app/br.com.goread.android-8.apk"],nativeLibraryDirectories=[/data/app-lib/br.com.goread.android-8, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5187)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4794) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4734) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:166) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1343) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5590) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by sgong-pdftron** [comment]
@ericksoncst Thanks for reporting this issue.

It seems the instruction page is missing enabling multi-dex in your app, it is added in https://github.com/PDFTron/pdftron-react-native/commit/627c0d6805e9952e8622991711fdb6996a2fce06, could you give it a try?

You can find a ready-to-run sample here as well https://github.com/PDFTron/react-native-sample. Thanks.

**Comment by ericksoncst** [comment]
@justinjung04 I tried, all guide info provided on docs was included

**Comment by sgong-pdftron** [comment]
@ericksoncst Did the updated sample project work for you? Thanks.

**Comment by ericksoncst** [comment]
@sgong-pdftron Yep, I started a new project and works. Thank u

**Comment by sgong-pdftron** [comment]
Thanks for the confirmation.
