### ISSUE TITLE
Annotation toolbar switcher causes app to crash

### ISSUE THREAD

**Issue by DHx64** [PDFTron/pdftron-react-native#609]
**Describe the bug**

Android app crash on toolbar menu change

**Steps to Reproduce the Problem**

1. git clone https://github.com/PDFTron/pdftron-react-native.git
2. cd pdftron-react-native/
3. yarn install
4. cd example
5. yarn install
6. yarn android
7. yarn start
8. open app on emulator 
9. change toolbar mode from view to annotations
10. change toolbar mode from annotations to view

**Expected behavior**
App should not crash when doing this.

**Screenshots**

https://giphy.com/gifs/IDoQSbLZ1MBY4zNObU

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android 
 - Device: Pixel 4
 - OS: Android 11.0, API 30

Same error replicated on:
 - Platform: Android 
 - Device: Nexus 5
 - OS: Android 9.0, API 28

**Additional context**

Chrash does not throw any error logs in console, so I installed sentry.io and got this stack trace from it.

Stack Trace(most recent call first)
```
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at com.pdftron.pdf.PDFViewCtrl.c(SourceFile:2165)
    at com.pdftron.pdf.PDFViewCtrl.onLayout(SourceFile:2036)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:20672)
    at android.view.ViewGroup.layout(ViewGroup.java:6194)
    at com.pdftron.reactnative.views.DocumentView$4.run(DocumentView.java:2086)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Sentry.io link to report -> https://sentry.io/share/issue/c188a35ed91147eeb2c4938833af9574/

In app if you first change your view mode from single to double and back, this bug dissapears, then app works like normal

Same issue encounterd when installing pdftron with npm @pdftron/react-native-pdf

My java configuration
```
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by darrenchann** [comment]
We're looking into this issue right now and will update you with a fix when it is ready.

**Comment by darrenchann** [comment]
Hi @DHx64 please refer to this PR to fix the crash issues with the view mode: https://github.com/PDFTron/pdftron-react-native/pull/611
